//go:build !ignore_autogenerated

// Copyright SmolAgents.
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	"encoding/json"

	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Agent) DeepCopyInto(out *Agent) {
	*out = *in
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Agent.
func (in *Agent) DeepCopy() *Agent {
	if in == nil {
		return nil
	}
	out := new(Agent)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentFSSpec) DeepCopyInto(out *AgentFSSpec) {
	*out = *in
	if in.Backup != nil {
		in, out := &in.Backup, &out.Backup
		*out = new(BackupPolicy)
		(*in).DeepCopyInto(*out)
	}
	if in.Restore != nil {
		in, out := &in.Restore, &out.Restore
		*out = new(RestorePolicy)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentFSSpec.
func (in *AgentFSSpec) DeepCopy() *AgentFSSpec {
	if in == nil {
		return nil
	}
	out := new(AgentFSSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentNetworkSpec) DeepCopyInto(out *AgentNetworkSpec) {
	*out = *in
	if in.AgentSelector != nil {
		in, out := &in.AgentSelector, &out.AgentSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.IdentityProxy != nil {
		in, out := &in.IdentityProxy, &out.IdentityProxy
		*out = new(IdentityProxySpec)
		(*in).DeepCopyInto(*out)
	}
	if in.WireGuardMesh != nil {
		in, out := &in.WireGuardMesh, &out.WireGuardMesh
		*out = new(WireGuardSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentNetworkSpec.
func (in *AgentNetworkSpec) DeepCopy() *AgentNetworkSpec {
	if in == nil {
		return nil
	}
	out := new(AgentNetworkSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentNetworkStatus) DeepCopyInto(out *AgentNetworkStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentNetworkStatus.
func (in *AgentNetworkStatus) DeepCopy() *AgentNetworkStatus {
	if in == nil {
		return nil
	}
	out := new(AgentNetworkStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentPolicy) DeepCopyInto(out *AgentPolicy) {
	*out = *in
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentPolicy.
func (in *AgentPolicy) DeepCopy() *AgentPolicy {
	if in == nil {
		return nil
	}
	out := new(AgentPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentPolicySpec) DeepCopyInto(out *AgentPolicySpec) {
	*out = *in
	if in.AllowedProviders != nil {
		in, out := &in.AllowedProviders, &out.AllowedProviders
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.AllowedTools != nil {
		in, out := &in.AllowedTools, &out.AllowedTools
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.MaxBudget != nil {
		in, out := &in.MaxBudget, &out.MaxBudget
		*out = new(Budget)
		**out = **in
	}
	if in.Redaction != nil {
		in, out := &in.Redaction, &out.Redaction
		*out = new(RedactionPolicy)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentPolicySpec.
func (in *AgentPolicySpec) DeepCopy() *AgentPolicySpec {
	if in == nil {
		return nil
	}
	out := new(AgentPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentRun) DeepCopyInto(out *AgentRun) {
	*out = *in
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentRun.
func (in *AgentRun) DeepCopy() *AgentRun {
	if in == nil {
		return nil
	}
	out := new(AgentRun)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentRunQuota) DeepCopyInto(out *AgentRunQuota) {
	*out = *in
	out.Spec = in.Spec
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentRunQuota.
func (in *AgentRunQuota) DeepCopy() *AgentRunQuota {
	if in == nil {
		return nil
	}
	out := new(AgentRunQuota)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentRunQuotaSpec) DeepCopyInto(out *AgentRunQuotaSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentRunQuotaSpec.
func (in *AgentRunQuotaSpec) DeepCopy() *AgentRunQuotaSpec {
	if in == nil {
		return nil
	}
	out := new(AgentRunQuotaSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentRunQuotaStatus) DeepCopyInto(out *AgentRunQuotaStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentRunQuotaStatus.
func (in *AgentRunQuotaStatus) DeepCopy() *AgentRunQuotaStatus {
	if in == nil {
		return nil
	}
	out := new(AgentRunQuotaStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentRunSpec) DeepCopyInto(out *AgentRunSpec) {
	*out = *in
	if in.Input != nil {
		in, out := &in.Input, &out.Input
		*out = make(json.RawMessage, len(*in))
		copy(*out, *in)
	}
	if in.BudgetOverride != nil {
		in, out := &in.BudgetOverride, &out.BudgetOverride
		*out = new(Budget)
		**out = **in
	}
	if in.Decision != nil {
		in, out := &in.Decision, &out.Decision
		*out = new(Decision)
		**out = **in
	}
	if in.RequireApprovalBeforeRun != nil {
		in, out := &in.RequireApprovalBeforeRun, &out.RequireApprovalBeforeRun
		*out = new(bool)
		**out = **in
	}
	if in.Inputs != nil {
		in, out := &in.Inputs, &out.Inputs
		*out = make([]RunInputFile, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentRunSpec.
func (in *AgentRunSpec) DeepCopy() *AgentRunSpec {
	if in == nil {
		return nil
	}
	out := new(AgentRunSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentSession) DeepCopyInto(out *AgentSession) {
	*out = *in
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentSession.
func (in *AgentSession) DeepCopy() *AgentSession {
	if in == nil {
		return nil
	}
	out := new(AgentSession)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentSessionSpec) DeepCopyInto(out *AgentSessionSpec) {
	*out = *in
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentSessionSpec.
func (in *AgentSessionSpec) DeepCopy() *AgentSessionSpec {
	if in == nil {
		return nil
	}
	out := new(AgentSessionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentSessionStatus) DeepCopyInto(out *AgentSessionStatus) {
	*out = *in
	if in.Runs != nil {
		in, out := &in.Runs, &out.Runs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Networks != nil {
		in, out := &in.Networks, &out.Networks
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	out.Usage = in.Usage
	if in.LastTurnTime != nil {
		in, out := &in.LastTurnTime, &out.LastTurnTime
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentSessionStatus.
func (in *AgentSessionStatus) DeepCopy() *AgentSessionStatus {
	if in == nil {
		return nil
	}
	out := new(AgentSessionStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentSpec) DeepCopyInto(out *AgentSpec) {
	*out = *in
	in.Model.DeepCopyInto(&out.Model)
	if in.Harness != nil {
		in, out := &in.Harness, &out.Harness
		*out = new(HarnessSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Tools != nil {
		in, out := &in.Tools, &out.Tools
		*out = make([]ToolRef, len(*in))
		copy(*out, *in)
	}
	if in.Storage != nil {
		in, out := &in.Storage, &out.Storage
		*out = new(StorageSpec)
		(*in).DeepCopyInto(*out)
	}
	out.Budget = in.Budget
	out.Identity = in.Identity
	out.Sandbox = in.Sandbox
	if in.Approval != nil {
		in, out := &in.Approval, &out.Approval
		*out = new(ApprovalPolicy)
		**out = **in
	}
	if in.Session != nil {
		in, out := &in.Session, &out.Session
		*out = new(SessionSpec)
		**out = **in
	}
	if in.Artifacts != nil {
		in, out := &in.Artifacts, &out.Artifacts
		*out = new(ArtifactSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentSpec.
func (in *AgentSpec) DeepCopy() *AgentSpec {
	if in == nil {
		return nil
	}
	out := new(AgentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentStatus) DeepCopyInto(out *AgentStatus) {
	*out = *in
	if in.ResolvedTools != nil {
		in, out := &in.ResolvedTools, &out.ResolvedTools
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentStatus.
func (in *AgentStatus) DeepCopy() *AgentStatus {
	if in == nil {
		return nil
	}
	out := new(AgentStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentTargetSpec) DeepCopyInto(out *AgentTargetSpec) {
	*out = *in
	out.Ref = in.Ref
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentTargetSpec.
func (in *AgentTargetSpec) DeepCopy() *AgentTargetSpec {
	if in == nil {
		return nil
	}
	out := new(AgentTargetSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentTeam) DeepCopyInto(out *AgentTeam) {
	*out = *in
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentTeam.
func (in *AgentTeam) DeepCopy() *AgentTeam {
	if in == nil {
		return nil
	}
	out := new(AgentTeam)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentTeamSpec) DeepCopyInto(out *AgentTeamSpec) {
	*out = *in
	if in.Members != nil {
		in, out := &in.Members, &out.Members
		*out = make([]TeamMemberSpec, len(*in))
		copy(*out, *in)
	}
	if in.Budget != nil {
		in, out := &in.Budget, &out.Budget
		*out = new(Budget)
		**out = **in
	}
	if in.Convergence != nil {
		in, out := &in.Convergence, &out.Convergence
		*out = new(ConvergenceSpec)
		**out = **in
	}
	if in.SharedWorkspace != nil {
		in, out := &in.SharedWorkspace, &out.SharedWorkspace
		*out = new(SharedWorkspaceSpec)
		**out = **in
	}
	if in.Hooks != nil {
		in, out := &in.Hooks, &out.Hooks
		*out = make([]TeamHookSpec, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentTeamSpec.
func (in *AgentTeamSpec) DeepCopy() *AgentTeamSpec {
	if in == nil {
		return nil
	}
	out := new(AgentTeamSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentTeamStatus) DeepCopyInto(out *AgentTeamStatus) {
	*out = *in
	if in.Members != nil {
		in, out := &in.Members, &out.Members
		*out = make([]TeamMemberStatus, len(*in))
		copy(*out, *in)
	}
	out.CumulativeUsage = in.CumulativeUsage
	if in.LastActivity != nil {
		in, out := &in.LastActivity, &out.LastActivity
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentTeamStatus.
func (in *AgentTeamStatus) DeepCopy() *AgentTeamStatus {
	if in == nil {
		return nil
	}
	out := new(AgentTeamStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentWorkflow) DeepCopyInto(out *AgentWorkflow) {
	*out = *in
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentWorkflow.
func (in *AgentWorkflow) DeepCopy() *AgentWorkflow {
	if in == nil {
		return nil
	}
	out := new(AgentWorkflow)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentWorkflowSpec) DeepCopyInto(out *AgentWorkflowSpec) {
	*out = *in
	if in.Nodes != nil {
		in, out := &in.Nodes, &out.Nodes
		*out = make([]WorkflowNode, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Edges != nil {
		in, out := &in.Edges, &out.Edges
		*out = make([]WorkflowEdge, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentWorkflowSpec.
func (in *AgentWorkflowSpec) DeepCopy() *AgentWorkflowSpec {
	if in == nil {
		return nil
	}
	out := new(AgentWorkflowSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentWorkflowStatus) DeepCopyInto(out *AgentWorkflowStatus) {
	*out = *in
	if in.NodeStates != nil {
		in, out := &in.NodeStates, &out.NodeStates
		*out = make([]NodeState, len(*in))
		copy(*out, *in)
	}
	out.CumulativeUsage = in.CumulativeUsage
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentWorkflowStatus.
func (in *AgentWorkflowStatus) DeepCopy() *AgentWorkflowStatus {
	if in == nil {
		return nil
	}
	out := new(AgentWorkflowStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApprovalPolicy) DeepCopyInto(out *ApprovalPolicy) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApprovalPolicy.
func (in *ApprovalPolicy) DeepCopy() *ApprovalPolicy {
	if in == nil {
		return nil
	}
	out := new(ApprovalPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArtifactRule) DeepCopyInto(out *ArtifactRule) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArtifactRule.
func (in *ArtifactRule) DeepCopy() *ArtifactRule {
	if in == nil {
		return nil
	}
	out := new(ArtifactRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArtifactSpec) DeepCopyInto(out *ArtifactSpec) {
	*out = *in
	if in.Outputs != nil {
		in, out := &in.Outputs, &out.Outputs
		*out = make([]ArtifactRule, len(*in))
		copy(*out, *in)
	}
	if in.S3 != nil {
		in, out := &in.S3, &out.S3
		*out = new(S3BackupSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArtifactSpec.
func (in *ArtifactSpec) DeepCopy() *ArtifactSpec {
	if in == nil {
		return nil
	}
	out := new(ArtifactSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArtifactStatusRef) DeepCopyInto(out *ArtifactStatusRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArtifactStatusRef.
func (in *ArtifactStatusRef) DeepCopy() *ArtifactStatusRef {
	if in == nil {
		return nil
	}
	out := new(ArtifactStatusRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArtifactsStatus) DeepCopyInto(out *ArtifactsStatus) {
	*out = *in
	if in.Refs != nil {
		in, out := &in.Refs, &out.Refs
		*out = make([]ArtifactStatusRef, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArtifactsStatus.
func (in *ArtifactsStatus) DeepCopy() *ArtifactsStatus {
	if in == nil {
		return nil
	}
	out := new(ArtifactsStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AttachGrant) DeepCopyInto(out *AttachGrant) {
	*out = *in
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AttachGrant.
func (in *AttachGrant) DeepCopy() *AttachGrant {
	if in == nil {
		return nil
	}
	out := new(AttachGrant)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AttachGrantSpec) DeepCopyInto(out *AttachGrantSpec) {
	*out = *in
	if in.ExpiresAt != nil {
		in, out := &in.ExpiresAt, &out.ExpiresAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AttachGrantSpec.
func (in *AttachGrantSpec) DeepCopy() *AttachGrantSpec {
	if in == nil {
		return nil
	}
	out := new(AttachGrantSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AttachGrantStatus) DeepCopyInto(out *AttachGrantStatus) {
	*out = *in
	if in.LastAttachTime != nil {
		in, out := &in.LastAttachTime, &out.LastAttachTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AttachGrantStatus.
func (in *AttachGrantStatus) DeepCopy() *AttachGrantStatus {
	if in == nil {
		return nil
	}
	out := new(AttachGrantStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuthRef) DeepCopyInto(out *AuthRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuthRef.
func (in *AuthRef) DeepCopy() *AuthRef {
	if in == nil {
		return nil
	}
	out := new(AuthRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BackupPolicy) DeepCopyInto(out *BackupPolicy) {
	*out = *in
	if in.S3 != nil {
		in, out := &in.S3, &out.S3
		*out = new(S3BackupSpec)
		(*in).DeepCopyInto(*out)
	}
	out.Retention = in.Retention
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BackupPolicy.
func (in *BackupPolicy) DeepCopy() *BackupPolicy {
	if in == nil {
		return nil
	}
	out := new(BackupPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Budget) DeepCopyInto(out *Budget) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Budget.
func (in *Budget) DeepCopy() *Budget {
	if in == nil {
		return nil
	}
	out := new(Budget)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BudgetExceededError) DeepCopyInto(out *BudgetExceededError) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BudgetExceededError.
func (in *BudgetExceededError) DeepCopy() *BudgetExceededError {
	if in == nil {
		return nil
	}
	out := new(BudgetExceededError)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ChunkSpec) DeepCopyInto(out *ChunkSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ChunkSpec.
func (in *ChunkSpec) DeepCopy() *ChunkSpec {
	if in == nil {
		return nil
	}
	out := new(ChunkSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConvergenceSpec) DeepCopyInto(out *ConvergenceSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConvergenceSpec.
func (in *ConvergenceSpec) DeepCopy() *ConvergenceSpec {
	if in == nil {
		return nil
	}
	out := new(ConvergenceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CredentialGrantSpec) DeepCopyInto(out *CredentialGrantSpec) {
	*out = *in
	if in.Repos != nil {
		in, out := &in.Repos, &out.Repos
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CredentialGrantSpec.
func (in *CredentialGrantSpec) DeepCopy() *CredentialGrantSpec {
	if in == nil {
		return nil
	}
	out := new(CredentialGrantSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CredentialInjection) DeepCopyInto(out *CredentialInjection) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CredentialInjection.
func (in *CredentialInjection) DeepCopy() *CredentialInjection {
	if in == nil {
		return nil
	}
	out := new(CredentialInjection)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Decision) DeepCopyInto(out *Decision) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Decision.
func (in *Decision) DeepCopy() *Decision {
	if in == nil {
		return nil
	}
	out := new(Decision)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DynamicCredentialBackendSpec) DeepCopyInto(out *DynamicCredentialBackendSpec) {
	*out = *in
	if in.GitHubApp != nil {
		in, out := &in.GitHubApp, &out.GitHubApp
		*out = new(GitHubAppBackendSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Grants != nil {
		in, out := &in.Grants, &out.Grants
		*out = make([]CredentialGrantSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DynamicCredentialBackendSpec.
func (in *DynamicCredentialBackendSpec) DeepCopy() *DynamicCredentialBackendSpec {
	if in == nil {
		return nil
	}
	out := new(DynamicCredentialBackendSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DynamicCredentialBackendStatus) DeepCopyInto(out *DynamicCredentialBackendStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DynamicCredentialBackendStatus.
func (in *DynamicCredentialBackendStatus) DeepCopy() *DynamicCredentialBackendStatus {
	if in == nil {
		return nil
	}
	out := new(DynamicCredentialBackendStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EgressPolicy) DeepCopyInto(out *EgressPolicy) {
	*out = *in
	if in.Allow != nil {
		in, out := &in.Allow, &out.Allow
		*out = make([]EgressRule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.RedirectCIDRs != nil {
		in, out := &in.RedirectCIDRs, &out.RedirectCIDRs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EgressPolicy.
func (in *EgressPolicy) DeepCopy() *EgressPolicy {
	if in == nil {
		return nil
	}
	out := new(EgressPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EgressRule) DeepCopyInto(out *EgressRule) {
	*out = *in
	if in.Ports != nil {
		in, out := &in.Ports, &out.Ports
		*out = make([]int32, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EgressRule.
func (in *EgressRule) DeepCopy() *EgressRule {
	if in == nil {
		return nil
	}
	out := new(EgressRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FanoutTargetSpec) DeepCopyInto(out *FanoutTargetSpec) {
	*out = *in
	out.Ref = in.Ref
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FanoutTargetSpec.
func (in *FanoutTargetSpec) DeepCopy() *FanoutTargetSpec {
	if in == nil {
		return nil
	}
	out := new(FanoutTargetSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FunctionSpec) DeepCopyInto(out *FunctionSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FunctionSpec.
func (in *FunctionSpec) DeepCopy() *FunctionSpec {
	if in == nil {
		return nil
	}
	out := new(FunctionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GatewayUIAuth) DeepCopyInto(out *GatewayUIAuth) {
	*out = *in
	if in.SecretRef != nil {
		in, out := &in.SecretRef, &out.SecretRef
		*out = new(AuthRef)
		**out = **in
	}
	if in.OIDC != nil {
		in, out := &in.OIDC, &out.OIDC
		*out = new(GatewayUIOIDC)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GatewayUIAuth.
func (in *GatewayUIAuth) DeepCopy() *GatewayUIAuth {
	if in == nil {
		return nil
	}
	out := new(GatewayUIAuth)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GatewayUIOIDC) DeepCopyInto(out *GatewayUIOIDC) {
	*out = *in
	if in.SecretRef != nil {
		in, out := &in.SecretRef, &out.SecretRef
		*out = new(AuthRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GatewayUIOIDC.
func (in *GatewayUIOIDC) DeepCopy() *GatewayUIOIDC {
	if in == nil {
		return nil
	}
	out := new(GatewayUIOIDC)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GatewayUISpec) DeepCopyInto(out *GatewayUISpec) {
	*out = *in
	in.Auth.DeepCopyInto(&out.Auth)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GatewayUISpec.
func (in *GatewayUISpec) DeepCopy() *GatewayUISpec {
	if in == nil {
		return nil
	}
	out := new(GatewayUISpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GitHubAppBackendSpec) DeepCopyInto(out *GitHubAppBackendSpec) {
	*out = *in
	out.PrivateKeyRef = in.PrivateKeyRef
	if in.ScopePermissions != nil {
		in, out := &in.ScopePermissions, &out.ScopePermissions
		*out = make(map[string]map[string]string, len(*in))
		for key, val := range *in {
			var outVal map[string]string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = make(map[string]string, len(*in))
				for key, val := range *in {
					(*out)[key] = val
				}
			}
			(*out)[key] = outVal
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GitHubAppBackendSpec.
func (in *GitHubAppBackendSpec) DeepCopy() *GitHubAppBackendSpec {
	if in == nil {
		return nil
	}
	out := new(GitHubAppBackendSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HTTPSpec) DeepCopyInto(out *HTTPSpec) {
	*out = *in
	if in.Auth != nil {
		in, out := &in.Auth, &out.Auth
		*out = new(AuthRef)
		**out = **in
	}
	if in.Headers != nil {
		in, out := &in.Headers, &out.Headers
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HTTPSpec.
func (in *HTTPSpec) DeepCopy() *HTTPSpec {
	if in == nil {
		return nil
	}
	out := new(HTTPSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HarnessCLISpec) DeepCopyInto(out *HarnessCLISpec) {
	*out = *in
	if in.ExtraFlags != nil {
		in, out := &in.ExtraFlags, &out.ExtraFlags
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.AllowedTools != nil {
		in, out := &in.AllowedTools, &out.AllowedTools
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.DisallowedTools != nil {
		in, out := &in.DisallowedTools, &out.DisallowedTools
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.MCPServers != nil {
		in, out := &in.MCPServers, &out.MCPServers
		*out = make([]MCPServerSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HarnessCLISpec.
func (in *HarnessCLISpec) DeepCopy() *HarnessCLISpec {
	if in == nil {
		return nil
	}
	out := new(HarnessCLISpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HarnessEnvVar) DeepCopyInto(out *HarnessEnvVar) {
	*out = *in
	if in.SecretRef != nil {
		in, out := &in.SecretRef, &out.SecretRef
		*out = new(AuthRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HarnessEnvVar.
func (in *HarnessEnvVar) DeepCopy() *HarnessEnvVar {
	if in == nil {
		return nil
	}
	out := new(HarnessEnvVar)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HarnessHTTPSpec) DeepCopyInto(out *HarnessHTTPSpec) {
	*out = *in
	if in.Headers != nil {
		in, out := &in.Headers, &out.Headers
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Auth != nil {
		in, out := &in.Auth, &out.Auth
		*out = new(AuthRef)
		**out = **in
	}
	if in.Retry != nil {
		in, out := &in.Retry, &out.Retry
		*out = new(RetrySpec)
		**out = **in
	}
	if in.ImagePolicy != nil {
		in, out := &in.ImagePolicy, &out.ImagePolicy
		*out = new(ImagePolicy)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HarnessHTTPSpec.
func (in *HarnessHTTPSpec) DeepCopy() *HarnessHTTPSpec {
	if in == nil {
		return nil
	}
	out := new(HarnessHTTPSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HarnessPiMonoSpec) DeepCopyInto(out *HarnessPiMonoSpec) {
	*out = *in
	if in.ExtraArgs != nil {
		in, out := &in.ExtraArgs, &out.ExtraArgs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HarnessPiMonoSpec.
func (in *HarnessPiMonoSpec) DeepCopy() *HarnessPiMonoSpec {
	if in == nil {
		return nil
	}
	out := new(HarnessPiMonoSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HarnessSpec) DeepCopyInto(out *HarnessSpec) {
	*out = *in
	if in.Command != nil {
		in, out := &in.Command, &out.Command
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Env != nil {
		in, out := &in.Env, &out.Env
		*out = make([]HarnessEnvVar, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.HTTP != nil {
		in, out := &in.HTTP, &out.HTTP
		*out = new(HarnessHTTPSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.CLI != nil {
		in, out := &in.CLI, &out.CLI
		*out = new(HarnessCLISpec)
		(*in).DeepCopyInto(*out)
	}
	if in.PiMono != nil {
		in, out := &in.PiMono, &out.PiMono
		*out = new(HarnessPiMonoSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HarnessSpec.
func (in *HarnessSpec) DeepCopy() *HarnessSpec {
	if in == nil {
		return nil
	}
	out := new(HarnessSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IdentityProxySpec) DeepCopyInto(out *IdentityProxySpec) {
	*out = *in
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = make([]ResourceTarget, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.Egress.DeepCopyInto(&out.Egress)
	if in.TTS != nil {
		in, out := &in.TTS, &out.TTS
		*out = new(TTSRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IdentityProxySpec.
func (in *IdentityProxySpec) DeepCopy() *IdentityProxySpec {
	if in == nil {
		return nil
	}
	out := new(IdentityProxySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IdentitySpec) DeepCopyInto(out *IdentitySpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IdentitySpec.
func (in *IdentitySpec) DeepCopy() *IdentitySpec {
	if in == nil {
		return nil
	}
	out := new(IdentitySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImagePolicy) DeepCopyInto(out *ImagePolicy) {
	*out = *in
	if in.AllowedURLHosts != nil {
		in, out := &in.AllowedURLHosts, &out.AllowedURLHosts
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImagePolicy.
func (in *ImagePolicy) DeepCopy() *ImagePolicy {
	if in == nil {
		return nil
	}
	out := new(ImagePolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MCPServerSpec) DeepCopyInto(out *MCPServerSpec) {
	*out = *in
	if in.Command != nil {
		in, out := &in.Command, &out.Command
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Env != nil {
		in, out := &in.Env, &out.Env
		*out = make([]HarnessEnvVar, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MCPServerSpec.
func (in *MCPServerSpec) DeepCopy() *MCPServerSpec {
	if in == nil {
		return nil
	}
	out := new(MCPServerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MCPSpec) DeepCopyInto(out *MCPSpec) {
	*out = *in
	if in.Auth != nil {
		in, out := &in.Auth, &out.Auth
		*out = new(AuthRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MCPSpec.
func (in *MCPSpec) DeepCopy() *MCPSpec {
	if in == nil {
		return nil
	}
	out := new(MCPSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MemoryCondition) DeepCopyInto(out *MemoryCondition) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MemoryCondition.
func (in *MemoryCondition) DeepCopy() *MemoryCondition {
	if in == nil {
		return nil
	}
	out := new(MemoryCondition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MemoryGrant) DeepCopyInto(out *MemoryGrant) {
	*out = *in
	if in.Operations != nil {
		in, out := &in.Operations, &out.Operations
		*out = make([]MemoryOperation, len(*in))
		copy(*out, *in)
	}
	if in.Namespaces != nil {
		in, out := &in.Namespaces, &out.Namespaces
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MemoryGrant.
func (in *MemoryGrant) DeepCopy() *MemoryGrant {
	if in == nil {
		return nil
	}
	out := new(MemoryGrant)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MemoryRetrieverSpec) DeepCopyInto(out *MemoryRetrieverSpec) {
	*out = *in
	if in.Stores != nil {
		in, out := &in.Stores, &out.Stores
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Namespaces != nil {
		in, out := &in.Namespaces, &out.Namespaces
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	out.Chunking = in.Chunking
	if in.Mount != nil {
		in, out := &in.Mount, &out.Mount
		*out = new(MountSpec)
		**out = **in
	}
	if in.Policy != nil {
		in, out := &in.Policy, &out.Policy
		*out = make([]MemoryGrant, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	out.Quota = in.Quota
	if in.AllowedMergePolicies != nil {
		in, out := &in.AllowedMergePolicies, &out.AllowedMergePolicies
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MemoryRetrieverSpec.
func (in *MemoryRetrieverSpec) DeepCopy() *MemoryRetrieverSpec {
	if in == nil {
		return nil
	}
	out := new(MemoryRetrieverSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MemoryRetrieverStatus) DeepCopyInto(out *MemoryRetrieverStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]MemoryCondition, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MemoryRetrieverStatus.
func (in *MemoryRetrieverStatus) DeepCopy() *MemoryRetrieverStatus {
	if in == nil {
		return nil
	}
	out := new(MemoryRetrieverStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MemoryStoreSpec) DeepCopyInto(out *MemoryStoreSpec) {
	*out = *in
	if in.Auth != nil {
		in, out := &in.Auth, &out.Auth
		*out = new(AuthRef)
		**out = **in
	}
	out.Tenancy = in.Tenancy
	if in.AgentFS != nil {
		in, out := &in.AgentFS, &out.AgentFS
		*out = new(AgentFSSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MemoryStoreSpec.
func (in *MemoryStoreSpec) DeepCopy() *MemoryStoreSpec {
	if in == nil {
		return nil
	}
	out := new(MemoryStoreSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MemoryStoreStatus) DeepCopyInto(out *MemoryStoreStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]MemoryCondition, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MemoryStoreStatus.
func (in *MemoryStoreStatus) DeepCopy() *MemoryStoreStatus {
	if in == nil {
		return nil
	}
	out := new(MemoryStoreStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelGatewaySpec) DeepCopyInto(out *ModelGatewaySpec) {
	*out = *in
	if in.Env != nil {
		in, out := &in.Env, &out.Env
		*out = make([]HarnessEnvVar, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	out.Sandbox = in.Sandbox
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
	if in.UI != nil {
		in, out := &in.UI, &out.UI
		*out = new(GatewayUISpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelGatewaySpec.
func (in *ModelGatewaySpec) DeepCopy() *ModelGatewaySpec {
	if in == nil {
		return nil
	}
	out := new(ModelGatewaySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelGatewayStatus) DeepCopyInto(out *ModelGatewayStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelGatewayStatus.
func (in *ModelGatewayStatus) DeepCopy() *ModelGatewayStatus {
	if in == nil {
		return nil
	}
	out := new(ModelGatewayStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelProvider) DeepCopyInto(out *ModelProvider) {
	*out = *in
	out.Spec = in.Spec
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelProvider.
func (in *ModelProvider) DeepCopy() *ModelProvider {
	if in == nil {
		return nil
	}
	out := new(ModelProvider)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelProviderSpec) DeepCopyInto(out *ModelProviderSpec) {
	*out = *in
	out.SecretRef = in.SecretRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelProviderSpec.
func (in *ModelProviderSpec) DeepCopy() *ModelProviderSpec {
	if in == nil {
		return nil
	}
	out := new(ModelProviderSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelProviderStatus) DeepCopyInto(out *ModelProviderStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelProviderStatus.
func (in *ModelProviderStatus) DeepCopy() *ModelProviderStatus {
	if in == nil {
		return nil
	}
	out := new(ModelProviderStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelRef) DeepCopyInto(out *ModelRef) {
	*out = *in
	if in.Temperature != nil {
		in, out := &in.Temperature, &out.Temperature
		*out = new(float64)
		**out = **in
	}
	if in.TopP != nil {
		in, out := &in.TopP, &out.TopP
		*out = new(float64)
		**out = **in
	}
	if in.MaxOutputTokens != nil {
		in, out := &in.MaxOutputTokens, &out.MaxOutputTokens
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelRef.
func (in *ModelRef) DeepCopy() *ModelRef {
	if in == nil {
		return nil
	}
	out := new(ModelRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MountSpec) DeepCopyInto(out *MountSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MountSpec.
func (in *MountSpec) DeepCopy() *MountSpec {
	if in == nil {
		return nil
	}
	out := new(MountSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeState) DeepCopyInto(out *NodeState) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeState.
func (in *NodeState) DeepCopy() *NodeState {
	if in == nil {
		return nil
	}
	out := new(NodeState)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PendingAction) DeepCopyInto(out *PendingAction) {
	*out = *in
	in.RequestedAt.DeepCopyInto(&out.RequestedAt)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PendingAction.
func (in *PendingAction) DeepCopy() *PendingAction {
	if in == nil {
		return nil
	}
	out := new(PendingAction)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Predicate) DeepCopyInto(out *Predicate) {
	*out = *in
	if in.path != nil {
		in, out := &in.path, &out.path
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Predicate.
func (in *Predicate) DeepCopy() *Predicate {
	if in == nil {
		return nil
	}
	out := new(Predicate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QuotaSpec) DeepCopyInto(out *QuotaSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QuotaSpec.
func (in *QuotaSpec) DeepCopy() *QuotaSpec {
	if in == nil {
		return nil
	}
	out := new(QuotaSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RedactionPolicy) DeepCopyInto(out *RedactionPolicy) {
	*out = *in
	if in.Patterns != nil {
		in, out := &in.Patterns, &out.Patterns
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RedactionPolicy.
func (in *RedactionPolicy) DeepCopy() *RedactionPolicy {
	if in == nil {
		return nil
	}
	out := new(RedactionPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceRequirements) DeepCopyInto(out *ResourceRequirements) {
	*out = *in
	if in.Limits != nil {
		in, out := &in.Limits, &out.Limits
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Requests != nil {
		in, out := &in.Requests, &out.Requests
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceRequirements.
func (in *ResourceRequirements) DeepCopy() *ResourceRequirements {
	if in == nil {
		return nil
	}
	out := new(ResourceRequirements)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceTarget) DeepCopyInto(out *ResourceTarget) {
	*out = *in
	if in.Authorize != nil {
		in, out := &in.Authorize, &out.Authorize
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.TraT != nil {
		in, out := &in.TraT, &out.TraT
		*out = new(TraTInjection)
		**out = **in
	}
	if in.Credential != nil {
		in, out := &in.Credential, &out.Credential
		*out = new(CredentialInjection)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceTarget.
func (in *ResourceTarget) DeepCopy() *ResourceTarget {
	if in == nil {
		return nil
	}
	out := new(ResourceTarget)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RestorePolicy) DeepCopyInto(out *RestorePolicy) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RestorePolicy.
func (in *RestorePolicy) DeepCopy() *RestorePolicy {
	if in == nil {
		return nil
	}
	out := new(RestorePolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RetentionPolicy) DeepCopyInto(out *RetentionPolicy) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RetentionPolicy.
func (in *RetentionPolicy) DeepCopy() *RetentionPolicy {
	if in == nil {
		return nil
	}
	out := new(RetentionPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RetrySpec) DeepCopyInto(out *RetrySpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RetrySpec.
func (in *RetrySpec) DeepCopy() *RetrySpec {
	if in == nil {
		return nil
	}
	out := new(RetrySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RunInputFile) DeepCopyInto(out *RunInputFile) {
	*out = *in
	if in.SecretRef != nil {
		in, out := &in.SecretRef, &out.SecretRef
		*out = new(AuthRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RunInputFile.
func (in *RunInputFile) DeepCopy() *RunInputFile {
	if in == nil {
		return nil
	}
	out := new(RunInputFile)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RunStatus) DeepCopyInto(out *RunStatus) {
	*out = *in
	if in.StartedAt != nil {
		in, out := &in.StartedAt, &out.StartedAt
		*out = (*in).DeepCopy()
	}
	if in.EndedAt != nil {
		in, out := &in.EndedAt, &out.EndedAt
		*out = (*in).DeepCopy()
	}
	if in.Steps != nil {
		in, out := &in.Steps, &out.Steps
		*out = make([]Step, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	out.Usage = in.Usage
	if in.Output != nil {
		in, out := &in.Output, &out.Output
		*out = make(json.RawMessage, len(*in))
		copy(*out, *in)
	}
	if in.PendingAction != nil {
		in, out := &in.PendingAction, &out.PendingAction
		*out = new(PendingAction)
		(*in).DeepCopyInto(*out)
	}
	if in.Trace != nil {
		in, out := &in.Trace, &out.Trace
		*out = new(TraceSummary)
		**out = **in
	}
	if in.Artifacts != nil {
		in, out := &in.Artifacts, &out.Artifacts
		*out = new(ArtifactsStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.Networks != nil {
		in, out := &in.Networks, &out.Networks
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RunStatus.
func (in *RunStatus) DeepCopy() *RunStatus {
	if in == nil {
		return nil
	}
	out := new(RunStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *S3BackupSpec) DeepCopyInto(out *S3BackupSpec) {
	*out = *in
	if in.CredentialsRef != nil {
		in, out := &in.CredentialsRef, &out.CredentialsRef
		*out = new(AuthRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new S3BackupSpec.
func (in *S3BackupSpec) DeepCopy() *S3BackupSpec {
	if in == nil {
		return nil
	}
	out := new(S3BackupSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SandboxSpec) DeepCopyInto(out *SandboxSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SandboxSpec.
func (in *SandboxSpec) DeepCopy() *SandboxSpec {
	if in == nil {
		return nil
	}
	out := new(SandboxSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SessionSpec) DeepCopyInto(out *SessionSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SessionSpec.
func (in *SessionSpec) DeepCopy() *SessionSpec {
	if in == nil {
		return nil
	}
	out := new(SessionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SharedWorkspaceSpec) DeepCopyInto(out *SharedWorkspaceSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SharedWorkspaceSpec.
func (in *SharedWorkspaceSpec) DeepCopy() *SharedWorkspaceSpec {
	if in == nil {
		return nil
	}
	out := new(SharedWorkspaceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Step) DeepCopyInto(out *Step) {
	*out = *in
	in.StartedAt.DeepCopyInto(&out.StartedAt)
	in.EndedAt.DeepCopyInto(&out.EndedAt)
	if in.ToolCalls != nil {
		in, out := &in.ToolCalls, &out.ToolCalls
		*out = make([]ToolCallRecord, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Step.
func (in *Step) DeepCopy() *Step {
	if in == nil {
		return nil
	}
	out := new(Step)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StorageSpec) DeepCopyInto(out *StorageSpec) {
	*out = *in
	if in.AgentFS != nil {
		in, out := &in.AgentFS, &out.AgentFS
		*out = new(AgentFSSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StorageSpec.
func (in *StorageSpec) DeepCopy() *StorageSpec {
	if in == nil {
		return nil
	}
	out := new(StorageSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TTSRef) DeepCopyInto(out *TTSRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TTSRef.
func (in *TTSRef) DeepCopy() *TTSRef {
	if in == nil {
		return nil
	}
	out := new(TTSRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TeamHookSpec) DeepCopyInto(out *TeamHookSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TeamHookSpec.
func (in *TeamHookSpec) DeepCopy() *TeamHookSpec {
	if in == nil {
		return nil
	}
	out := new(TeamHookSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TeamMemberSpec) DeepCopyInto(out *TeamMemberSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TeamMemberSpec.
func (in *TeamMemberSpec) DeepCopy() *TeamMemberSpec {
	if in == nil {
		return nil
	}
	out := new(TeamMemberSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TeamMemberStatus) DeepCopyInto(out *TeamMemberStatus) {
	*out = *in
	out.Usage = in.Usage
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TeamMemberStatus.
func (in *TeamMemberStatus) DeepCopy() *TeamMemberStatus {
	if in == nil {
		return nil
	}
	out := new(TeamMemberStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TenancySpec) DeepCopyInto(out *TenancySpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TenancySpec.
func (in *TenancySpec) DeepCopy() *TenancySpec {
	if in == nil {
		return nil
	}
	out := new(TenancySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Tool) DeepCopyInto(out *Tool) {
	*out = *in
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Tool.
func (in *Tool) DeepCopy() *Tool {
	if in == nil {
		return nil
	}
	out := new(Tool)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ToolCallRecord) DeepCopyInto(out *ToolCallRecord) {
	*out = *in
	if in.Arguments != nil {
		in, out := &in.Arguments, &out.Arguments
		*out = make(json.RawMessage, len(*in))
		copy(*out, *in)
	}
	if in.Result != nil {
		in, out := &in.Result, &out.Result
		*out = make(json.RawMessage, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ToolCallRecord.
func (in *ToolCallRecord) DeepCopy() *ToolCallRecord {
	if in == nil {
		return nil
	}
	out := new(ToolCallRecord)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ToolRef) DeepCopyInto(out *ToolRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ToolRef.
func (in *ToolRef) DeepCopy() *ToolRef {
	if in == nil {
		return nil
	}
	out := new(ToolRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ToolSpec) DeepCopyInto(out *ToolSpec) {
	*out = *in
	if in.InputSchema != nil {
		in, out := &in.InputSchema, &out.InputSchema
		*out = make(json.RawMessage, len(*in))
		copy(*out, *in)
	}
	if in.OutputSchema != nil {
		in, out := &in.OutputSchema, &out.OutputSchema
		*out = make(json.RawMessage, len(*in))
		copy(*out, *in)
	}
	if in.MCP != nil {
		in, out := &in.MCP, &out.MCP
		*out = new(MCPSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.HTTP != nil {
		in, out := &in.HTTP, &out.HTTP
		*out = new(HTTPSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Agent != nil {
		in, out := &in.Agent, &out.Agent
		*out = new(AgentTargetSpec)
		**out = **in
	}
	if in.Function != nil {
		in, out := &in.Function, &out.Function
		*out = new(FunctionSpec)
		**out = **in
	}
	if in.Fanout != nil {
		in, out := &in.Fanout, &out.Fanout
		*out = new(FanoutTargetSpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ToolSpec.
func (in *ToolSpec) DeepCopy() *ToolSpec {
	if in == nil {
		return nil
	}
	out := new(ToolSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TraTInjection) DeepCopyInto(out *TraTInjection) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TraTInjection.
func (in *TraTInjection) DeepCopy() *TraTInjection {
	if in == nil {
		return nil
	}
	out := new(TraTInjection)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TraceSummary) DeepCopyInto(out *TraceSummary) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TraceSummary.
func (in *TraceSummary) DeepCopy() *TraceSummary {
	if in == nil {
		return nil
	}
	out := new(TraceSummary)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Usage) DeepCopyInto(out *Usage) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Usage.
func (in *Usage) DeepCopy() *Usage {
	if in == nil {
		return nil
	}
	out := new(Usage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WGPeer) DeepCopyInto(out *WGPeer) {
	*out = *in
	if in.AllowedIPs != nil {
		in, out := &in.AllowedIPs, &out.AllowedIPs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.PSKRef != nil {
		in, out := &in.PSKRef, &out.PSKRef
		*out = new(AuthRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WGPeer.
func (in *WGPeer) DeepCopy() *WGPeer {
	if in == nil {
		return nil
	}
	out := new(WGPeer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WireGuardSpec) DeepCopyInto(out *WireGuardSpec) {
	*out = *in
	out.PrivateKeyRef = in.PrivateKeyRef
	if in.Addresses != nil {
		in, out := &in.Addresses, &out.Addresses
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.DNS != nil {
		in, out := &in.DNS, &out.DNS
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Peers != nil {
		in, out := &in.Peers, &out.Peers
		*out = make([]WGPeer, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WireGuardSpec.
func (in *WireGuardSpec) DeepCopy() *WireGuardSpec {
	if in == nil {
		return nil
	}
	out := new(WireGuardSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkflowEdge) DeepCopyInto(out *WorkflowEdge) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkflowEdge.
func (in *WorkflowEdge) DeepCopy() *WorkflowEdge {
	if in == nil {
		return nil
	}
	out := new(WorkflowEdge)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkflowNode) DeepCopyInto(out *WorkflowNode) {
	*out = *in
	if in.Input != nil {
		in, out := &in.Input, &out.Input
		*out = make(json.RawMessage, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkflowNode.
func (in *WorkflowNode) DeepCopy() *WorkflowNode {
	if in == nil {
		return nil
	}
	out := new(WorkflowNode)
	in.DeepCopyInto(out)
	return out
}
